baseURL = "https://jimrich.sk/"
title = "Jaroslav IMRICH - Open Source Developer" 
theme = "jimrich.sk"
languageCode = "en"

# Disables automatic interpretation of fractions with sub and sup elements
[blackfriday]
  fractions = false
 
# Disables building of "tags" and "categories"
[taxonomies]

# Tell the default Markdown renderer, which is Goldmark, to render raw HTML
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
